# Generated by Django 4.1.6 on 2023-02-02 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='reservation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bookings',
            name='reservation_slot',
            field=models.SmallIntegerField(default=10),
        ),
    ]
