# Generated by Django 4.1.6 on 2023-02-04 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='date_purchased',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
