# Generated by Django 4.1.6 on 2023-02-04 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_menu_date_purchased'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='date_purchased',
            new_name='date_ordered',
        ),
    ]
